name: skills
channels:
  - conda-forge
dependencies:
  - python=3.10
  - r-essentials
  - r-base
  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - sqlalchemy
  - schedule
  - pandas
  - scikit-learn
  - pip:
    - python-dotenv
    - mkdocs
    - boxsdk[jwt]
    - pyyaml
    - polars[all]
    - openpyxl
    - graphviz
    - sf-hamilton[visualization]
    - plotnine
    - pytest
    - geopy
    - geopandas
    - shapely
    - -e .
