---
title: "SAMS Data Exploratory (ITI)"
author: "Yashaswi Mohanty"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: journal
    toc: yes
    toc_float:
      collapsed: true
---



```{r Import libraries, echo=FALSE, include=FALSE}
source("paths.R")
library(RSQLite)
library(tidyverse)

```

```{r DB Connection, include=FALSE}

db_path = file.path(raw_data,"sams.db")


if (!file.exists(db_path)) {
  stop("Database file does not exist: ", db_path)
}

# Connect to database
con <- dbConnect(RSQLite::SQLite(), dbname = db_path)

# Load data
query <- "SELECT * FROM students WHERE module = 'ITI' AND sams_code IS NOT NULL;"

iti_data <- dbGetQuery(con, query) 


```

```{r Counting unique students, include=FALSE}
# Count number of unique obs
aadhar <- n_distinct(iti_data$aadhar_no)
year_min <- min(iti_data$academic_year)
year_max <- max(iti_data$academic_year)
```

# The vocational pipeline
There have been `r aadhar` ITI students in Odisha from academic years `r year_min` to `r year_max`. The
```{r}

```

