---
title: "SAMS Data Analysis"
author: "Data, Policy, and Innovation Centre"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  word_document:
    reference_docx: "template.docx"
    toc: true
    toc_depth: 3
    fig_caption: true
    keep_md: false           # Choose whether to keep the intermediate .md file
    df_print: paged         # Prints data frames as paginated tables
---

```{r Load configuration, include=FALSE, eval=FALSE, echo=FALSE}
library(here)
rm(list = ls())

here::i_am("README.md")
here()
source(file.path(here(),"scripts","config.R"))


```

```{r Libraries, include=FALSE, echo=FALSE}
library(tidyverse)
library(arrow)
library(ggplot2)
library(openxlsx)
library(kableExtra)
library(knitr)
```

```{r Load processed data, include=FALSE, echo=FALSE}
# Processed data
iti_marks_and_cutoffs <- read_parquet(get_path("iti_marks_and_cutoffs"))
iti_vacancies <- read_parquet(get_path("iti_vacancies"))
```


```{r Load interim data, include=FALSE, echo=FALSE}
# Interim data
iti_enrollments <- read_parquet(get_path("iti_enrollments"))
iti_enrollments_2023 <- iti_enrollments %>% filter(academic_year == 2023)
```


```{r Load output tables, include=FALSE, echo=FALSE}
quals_excel_path <- file.path(paths$TABLES_DIR,"trades_by_qualification.xlsx")
sheet_names <- getSheetNames(quals_excel_path)
trades_by_quals <- read.xlsx(
  quals_excel_path,
  sheet_names[1]
)
trades_by_quals_pct <- read.xlsx(
  quals_excel_path,
  sheet_names[2]
)

```

# Raw exhibits

* Our goal is to figure out why people choose vocational training / certain trades
    * Is it voluntary or are they pushed into it?

## Highest qualifications

```{r Highest qualifications raw, include=TRUE}
 trades_by_quals %>% kable( caption = "Sample Table") %>%
  kable_styling(full_width = F, bootstrap_options = c("striped", "hover"))
```


## Boards, marks, and cutoffs

## Distances

## Prices

## Quantities / Subscription

## Gender

Government is fixing both prices and quantities. 




