datasets:
  sams:
    type: SQLite
    path: "data/raw/sams.db"
    layer: raw

  iti_addresses:
    type: csv
    path: "data/external/iti_addresses.csv"
    layer: external

  block_shapefiles:
    type: shapefile
    path: "data/external/shapefiles_odisha/block_boundaries/Odisha_Admin_Block_BND_2021.shp"
    layer: external

  district_shapefiles:
    type: shapefile
    path: "data/external/shapefiles_odisha/district_boundaries/Odisha_Admin_District_BND_2021.shp"
    layer: external

  state_shapefiles:
    type: shapefile
    path: "data/external/shapefiles_india/India_State_Boundary.shp"
    layer: external

  india_border_shapefiles:
    type: shapefile
    path: "data/external/shapefiles_india/India_Country_Boundary.shp"
    layer: external
    
  village_populations:
    type: csv
    path: "data/external/all_districts_villages.csv"
    layer: external

  geocodes:
    type: parquet
    path: "data/interim/geocodes.pq"
    layer: interim 

  iti_enrollments:
    type: parquet
    path: "data/interim/iti_enrollments.pq"
    layer: interim

  iti_marks:
    type: parquet
    path: "data/interim/iti_marks.pq"
    layer: interim

  diploma_enrollments:
    type: parquet
    path: "data/interim/diploma_enrollments.pq"
    layer: interim

  diploma_marks:
    type: parquet
    path: "data/interim/diploma_marks.pq"
    layer: interim

  pdis_enrollments:
    type: parquet
    path: "data/interim/pdis_enrollments.pq"
    layer: interim

  pdis_marks:
    type: parquet
    path: "data/interim/pdis_marks.pq"
    layer: interim

  iti_institutes_strength:
    type: parquet
    path: "data/interim/iti_institutes_strength.pq"
    layer: interim

  iti_institutes_cutoffs:
    type: parquet
    path: "data/interim/iti_institutes_cutoffs.pq"
    layer: interim

  iti_institutes_enrollments:
    type: parquet
    path: "data/interim/iti_institutes_enrollments.pq"
    layer: interim

  diploma_institutes_strength:
    type: parquet
    path: "data/interim/diploma_institutes_strength.pq"
    layer: interim

  diploma_institutes_cutoffs:
    type: parquet
    path: "data/interim/diploma_institutes_cutoffs.pq"
    layer: interim

  diploma_institutes_enrollments:
    type: parquet
    path: "data/interim/diploma_institutes_enrollments.pq"
    layer: interim

  iti_marks_and_cutoffs:
    type: parquet
    path: "data/processed/iti_marks_and_cutoffs.pq"
    layer: processed

  iti_vacancies:
    type: parquet
    path: "data/processed/iti_vacancies.pq"
    layer: processed
  
  hss_enrollments:
    type: parquet
    path: "data/interim/hss_enrollments.pq"
    layer: interim

  hss_applications:
    type: parquet
    path: "data/interim/hss_applications.pq"
    layer: interim

  hss_marks:
    type: parquet
    path: "datcleara/interim/hss_marks.pq"
    layer: interim

  hss_first_choice_admissions:
    type: parquet
    path: "data/interim/hss_first_choice_admissions.pq"
    layer: interim

  deg_enrollments:
    type: parquet
    path: "data/interim/deg_enrollments.pq"
    layer: interim



exhibits:
  students_enrollment_basics:
    type: excel
    path: "output/tables/enrollment.xlsx"

  institutes_basics:
    type: excel
    path: "output/tables/institutes.xlsx"

  trades_and_branches_basics:
    type: excel
    path: "output/tables/trades_and_branches.xlsx"

  pipeline:
    type: excel
    input_path: "output/tables/static/pipeline.xlsx"
    output_path: "output/tables/pipeline.xlsx" 
  
  uc_exhibits:
    type: excel
    path: "output/tables/uc_exhibits.xlsx"
